language: java
before_script:
  - ant jar -v
  - ant -f src/main/integrator.xml strict -v
script: ant test -v
env: CLASSPATH=src/main/lib/commons-codec-1.4.jar:src/main/lib/icu4j.jar:src/main/lib/saxon/saxon9-dom.jar:src/main/lib/saxon/saxon9.jar:src/main/output2:src/main/lib/:src/main/lib/resolver.jar